### ISSUE TITLE
KeyError: '__origin__' when using lists

### ISSUE THREAD

**Issue by TrevorBagels** [ramazanpolat/prodict#21]
Python version: 3.9.2
OS: macOS Catalina

Seems to happen whenever I include a list in my dictionary and call `from_dict`

Code
```py
from prodict import Prodict

class BotConfig(Prodict):
	name: str
	token: str

class Config(Prodict):
	max_request_attempts: int
	seeds: list[str]
	bots: list[BotConfig]
	api_call_delay: float

data =	{
		'bots': [
			{'token': '[redacted]',
			'usertoken': '[also redacted]', 
			'name': '[another redacted thing]'}], 
	'seeds': ['[redacted]', '[redacted]'], 
	'api_call_delay': 0.0,
	'max_request_attempts': 5.0
	}

#breaks
config = Config.from_dict(data)

#works
config = Prodict.from_dict(data)
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/bagel/Documents/projects/discordmapper/prodictissue.py", line 28, in <module>
    config = Config.from_dict(data)
  File "/usr/local/lib/python3.9/site-packages/prodict/__init__.py", line 77, in from_dict
    val: cls = cls(**d)
  File "/usr/local/lib/python3.9/site-packages/prodict/__init__.py", line 47, in __init__
    self_d921dfa9_4e93_4123_893d_a7e7eb783a32.set_attributes(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/prodict/__init__.py", line 249, in set_attributes
    self_d921dfa9_4e93_4123_893d_a7e7eb783a32.set_attribute(k, v)
  File "/usr/local/lib/python3.9/site-packages/prodict/__init__.py", line 191, in set_attribute
    constructor, element_type = self.get_constructor(attr_name, value)
  File "/usr/local/lib/python3.9/site-packages/prodict/__init__.py", line 166, in get_constructor
    if attr_type1.__dict__['__origin__'] is list:
KeyError: '__origin__'
```

**Comment by TrevorBagels** [comment]
Found a fix for this, editing line 166 of __init__.py from 
`if attr_type1.__dict__['__origin__'] is list:`
to 
`if attr_type1.__origin__ is list:`
completely fixes it for me. Might be an issue with python 3.9, idk.

**Comment by ramazanpolat** [comment]
I believe this is because of Python 3.9.

Damn they always change the internals : (

That makes it insanely hard to implement since we will still need to support Python 3.8.

Having a switch to check the python version and running a different code based on the python version is really unmanageable.

Anyway, will check it ASAP.
