### ISSUE TITLE
Nested vanilla dicts don't survive pickle round trip

### ISSUE THREAD

**Issue by andrewmellinger** [ramazanpolat/prodict#24]
Greetings!

It appears that nested raw "dict" models don't survive round-tripping via pickle. I have a config object that I load into a prodict model that has an arbitrary "extension point" that I typed as dict. When the Prodict is serialized via pickle the dict is turned into Prodict then when it is read back Prodict sees a `Prodict` value but the type annotation is `dict.` 

Why do I do this? Well, my Prodict is automatically serialized because I am doing a multiprocessing Pool.

I imagine I could probably find some workarounds (such as using raw Prodicts instead of dicts), but it seems like this should work.

My sample code is this:

```
#! /usr/bin/env python3

import pickle

from prodict import Prodict


class InnerClass(Prodict):
    other_dict: dict


class MyData(Prodict):
    inner_obj: InnerClass


class AppModel():
    def __init__(self, my_data: MyData):
        self.my_data = my_data


if __name__ == '__main__':
    my_data: MyData = MyData.from_dict(
        {
            "inner_obj": {
                'other_dict': {"num_classes": 3}
            }
        })
    app = AppModel(my_data)

    p = pickle.dumps(app)
    app2 = pickle.loads(p)
``` 

The exception I get is:
```
Traceback (most recent call last):
  File "./prodict_test/pickle_test.py", line 31, in <module>
    app2 = pickle.loads(p)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 63, in __setstate__
    return Prodict.from_dict(state)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 81, in from_dict
    val: cls = cls(**d)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 51, in __init__
    self_d921dfa9_4e93_4123_893d_a7e7eb783a32.set_attributes(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 252, in set_attributes
    self_d921dfa9_4e93_4123_893d_a7e7eb783a32.set_attribute(k, v)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 219, in set_attribute
    self.update({attr_name: constructor(value)})
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 81, in from_dict
    val: cls = cls(**d)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 51, in __init__
    self_d921dfa9_4e93_4123_893d_a7e7eb783a32.set_attributes(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 252, in set_attributes
    self_d921dfa9_4e93_4123_893d_a7e7eb783a32.set_attribute(k, v)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 194, in set_attribute
    constructor, element_type = self.get_constructor(attr_name, value)
  File "/usr/local/lib/python3.8/site-packages/prodict/__init__.py", line 157, in get_constructor
    constructor = attr_type1.from_dict
AttributeError: type object 'dict' has no attribute 'from_dict'
```

If I annotate like  157 the specific field that it doesn't like is the `other_dict` is type of `dict` but the type of the value is "Prodict."

Thanks for any help!

**Comment by ramazanpolat** [comment]
If you want `inner_dict` to be type of `dict`, instead of `Prodict` then you won't be able to use benefits for `Prodict` for `inner_dict`.

In that case, you can certainly hint at its type as `Any` which will work.

```py
class InnerClass(Prodict):
    other_dict: Any


class MyData(Prodict):
    inner_obj: InnerClass


class AppModel:
    def __init__(self, my_data: MyData):
        self.my_data = my_data



if __name__ == "__main__":
    the_data: MyData = MyData.from_dict(
        {
            "inner_obj": {
                'other_dict': {"num_classes": 3}
            }
        })

    app = AppModel(the_data)
    p = pickle.dumps(app)
    app2: AppModel = pickle.loads(p)
    # print(type(app2.my_data.inner_obj), app2.my_data.inner_obj)
    assert isinstance(app2.my_data.inner_obj, dict)

```

**Comment by andrewmellinger** [comment]
I've switched to using Prodict everywhere instead of Any and it seems to work fine without any other issues.  So I am going to close this.
