### ISSUE TITLE
Error when setting value of Pandas cell to an object that itself uses Prodict objects

### ISSUE THREAD

**Issue by jonhandlermd** [ramazanpolat/prodict#26]
Hi -- Prodict is great.  I found an issue.  When I attempt to set the value of a Pandas cell to that of an object that itself uses Prodict objects, I get an error:

File "C:\Miniconda2\envs\My code\lib\site-packages\pandas\core\dtypes\generic.py", line 45, in _check
    return getattr(inst, attr, "_typ") in comp
  File "C:\Miniconda2\envs\My code\lib\site-packages\prodict\__init__.py", line 259, in __getattr__
    return self[item]
KeyError: '_typ'

Suggestions?

Thanks!

**Comment by ramazanpolat** [comment]
Can you show some peace of code to reproduce this?

**Comment by jonhandlermd** [comment]
Hi, 

The error I receive is:

———
Traceback (most recent call last):
  File "/Users/Jonathan/Library/Python/3.8/lib/python/site-packages/prodict/__init__.py", line 255, in __getattr__
    return self[item]
KeyError: '_typ'
Exception ignored in: 'pandas._libs.tslibs.util.is_period_object'
Traceback (most recent call last):
  File "/Users/Jonathan/Library/Python/3.8/lib/python/site-packages/prodict/__init__.py", line 255, in __getattr__
    return self[item]
KeyError: '_typ'
Traceback (most recent call last):
  File "/Users/Jonathan/Library/Python/3.8/lib/python/site-packages/prodict/__init__.py", line 255, in __getattr__
    return self[item]
KeyError: '_typ'
Exception ignored in: 'pandas._libs.lib.is_interval'
Traceback (most recent call last):
  File "/Users/Jonathan/Library/Python/3.8/lib/python/site-packages/prodict/__init__.py", line 255, in __getattr__
    return self[item]
KeyError: ‘_typ'
———

Below is some sample code.  If you set the “path_to_run” variable to 1 then it will run without error (or at least it runs without error for me).  If you set the “path_to_run” variable to 2 then it will error out.  
################################
# IMPORTS
################################
from prodict import Prodict as prodict
import pandas

#################################
# Main program
#################################
def main():

    path_to_run = 2

    if path_to_run == 1:
        my_dict = {}
        pandas_dictionary = {}
        pandas_dictionary['dict'] = [my_dict, my_dict, my_dict, my_dict]
        pandas_dictionary['integer'] = [1, 2, 3, 4]
        my_pandas = pandas.DataFrame(data=pandas_dictionary)
    else:
        my_prodict = prodict()
        pandas_dictionary = {}
        pandas_dictionary['prodict'] = [my_prodict, my_prodict, my_prodict, my_prodict]
        pandas_dictionary['integer'] = [1, 2, 3, 4]
        my_pandas = pandas.DataFrame(data=pandas_dictionary)

    #### All done!
    exit()


########################
# Classic ending
########################
if __name__ == '__main__':
    main()


Thanks!!

Jon

**Comment by ramazanpolat** [comment]
You can convert a Prodict to dict before trying to insert into a DataFrame:

```py
my_prodict = Prodict().to_dict()
pandas_dictionary = {}
pandas_dictionary['prodict'] = [my_prodict, my_prodict, my_prodict, my_prodict]
pandas_dictionary['integer'] = [1, 2, 3, 4]
my_pandas = pandas.DataFrame(data=pandas_dictionary)
```

**Comment by jonhandlermd** [comment]
Thanks.  I should have sent a more complex object in my example.

The problem is that I often have arbitrarily more complex objects, and the value of some attributes of those complex, nested objects may be Prodicts.  If I attempt to put any object containing a Prodict into the data frame then I get the error. Traversing evert complex object to find all the Prodicts and convert them to dicts is problematic because:

It's difficult to do.
It adds complexity to every code snippet moving Prodicts in and out of data frames.
It defeats the goal of using Prodicts to use dotted object notation with dictionaries.

Is there a way to enable objects that have values of attributes that are Prodicts to be put into Pandas data frames without first requiring the Prodicts to be converted to dictionaries?

Thanks!

Jon

**Comment by ramazanpolat** [comment]
> Is there a way to enable objects that have values of attributes that are Prodicts to be put into Pandas data frames without first requiring the Prodicts to be converted to dictionaries?

Sorry but I've checked the Pandas code and saw that Pandas does some conversion on the dict which Prodict is not comfortable with. I'm nowhere near being a Pandas expert therefore I couldn't sort it out.
