### ISSUE TITLE
getattr() should raise AttributeError

### ISSUE THREAD

**Issue by adm271828** [ramazanpolat/prodict#47]
Hi,

I don't know if this is maintained anymore, but I would suggest that `getattr()` raises an `AttributeError` instead of `KeyError`.

This would avoid breaking other libraries that expect `getattr()` ro raise an `AttributeError` such as Jinja2 for instance (but not only, also had trouble with `omegaconf` when creating a `DictConfig` from `Prodict`).

Best regards,

Antoine

```
    def __getattr__(self, item):
        try:
            return self[item]
        except KeyError as exc:
            raise AttributeError(str(exc))
```

**Comment by ramazanpolat** [comment]
Thank you for noticing.
You've touched a sketchy part.
Although we treat each entry as an attribute of the `Prodict` object, they are actually keys of the underlying dictinary. Therefore they need to conform dictionary errors. For dictionaries, whenever a non-existing key is referred, KeyError is thrown:

```py
>>> {'a':1, 'b':2}['a']   
1
>>> {'a':1, 'b':2}['c'] 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'c'
>>>
```

**Comment by adm271828** [comment]
Hi,

Not sure I understand your answer. But I guess you didn't fix it.

The point is not to raise an AttributeError when getitem is called. It
should raise a KeyError as for regular dict (your example).

The point is to raise an AttributeError when getattr is called! Which is
what my proposal do. Otherwise you don't comply to getattr interface. And
since regular dict do not implement getattr, there is no conflict at all or
expectation to raise a KeyError.

Do I miss something?

For the record I was ready to get rid of Prodict (to much problems with
other packages that use getattr). Until I understood where the problem came
from...

Best regards,

Antoine

Le lun. 18 nov. 2024 à 08:00, Ramazan Polat ***@***.***> a
écrit :

**Comment by adm271828** [comment]
@ramazanpolat I think you should consider reopening the issue.

Best regards.

**Comment by adm271828** [comment]
Looking at traceback and error message, a better implementation:

```python
    def __getattr__(self, item):
        try:
            return self[item]
        except KeyError as exc:
            raise AttributeError(f"{type(self).__name__!r} object has no attribute {exc!s}") from None
```

**Comment by adm271828** [comment]
Thanks!
Should probably work.

But unfortunately pip refuses to install the latest version (even after uninstalling prodict and purging pip cache). It downloads 0.8.19 and then reverts to 0.8.18:

```shell
> pip install prodict
Collecting prodict
  Downloading prodict-0.8.19.tar.gz (4.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/93/79/70cac0ab53a138953e5a6f1cc0e94e4034432ef150b7b6d6810da3049435/prodict-0.8.19.tar.gz (from https://pypi.org/simple/prodict/): Requested prodict from https://files.pythonhosted.org/packages/93/79/70cac0ab53a138953e5a6f1cc0e94e4034432ef150b7b6d6810da3049435/prodict-0.8.19.tar.gz has inconsistent version: expected '0.8.19', 
but metadata has '0.1.0'
  Downloading prodict-0.8.18.tar.gz (4.2 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: prodict
  Building wheel for prodict (pyproject.toml) ... done
  Created wheel for prodict: filename=prodict-0.8.18-py3-none-any.whl size=4212 sha256=562b6339e1ab7c8ee6036aab39cb1c738826e2373be486def3bd2a19892835bd
  Stored in directory: c:\users\ademaricourt\appdata\local\pip\cache\wheels\fd\87\81\a123a0a71626a2232062e76a4cea404adf3bdf7f24938c8452
Successfully built prodict
Installing collected packages: prodict
Successfully installed prodict-0.8.18
```

**Comment by ramazanpolat** [comment]
Thank you for testing.
Please uninstall it first and the install it again.
It should be working now.

```
pip install prodict
Collecting prodict
  Downloading prodict-0.8.20.tar.gz (4.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: prodict
  Building wheel for prodict (pyproject.toml) ... done
  Created wheel for prodict: filename=prodict-0.8.20-py3-none-any.whl size=3917 sha256=afd2e3ea5e8e37ecc2a892650ce64d2aa6a177d1a7ffc603403a4e0c6f1b6f0b
  Stored in directory: /Users/polat/Library/Caches/pip/wheels/89/ef/41/ce7bdcd6ab751d41376308f0319b590e9c40f6686c6a26215c
Successfully built prodict
Installing collected packages: prodict
Successfully installed prodict-0.8.20
python3 
Python 3.12.5 (v3.12.5:ff3bc82f7c9, Aug  7 2024, 05:32:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prodict import Prodict
>>> p = Prodict()
>>> p = Prodict.from_dict({'a':1, 'b':2})
>>> p
{'a': 1, 'b': 2}
>>> p.a
1
>>> p.b
2
>>> p.c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/prodict/__init__.py", line 213, in __getattr__
    raise AttributeError(f"{type(self).__name__!r} object has no attribute {exc!s}") from None
AttributeError: 'Prodict' object has no attribute 'c'
>>> p.'c'
  File "<stdin>", line 1
    p.'c'
      ^^^
SyntaxError: invalid syntax
>>> p['c']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'c'
>>> 
```

**Comment by adm271828** [comment]
OK, it works now.
Both install from pip and expected `getattr` behaviour!

Thank you for taking this issue into consideration

Antoine
