### ISSUE TITLE
TypeError: 'NoneType' object is not callable when deepcopy

### ISSUE THREAD

**Issue by ramazanpolat** [ramazanpolat/prodict#6]
Deepcopying and instance of `prodict` is faced with `TypeError: 'NoneType' object is not callable` error. Thanks to @JoaquinRives.

```
gen1 = Gene(name='gen1', encoding='categorical', categorical_values=['v11', 'v21'])
gen2 = Gene(name='gen2', encoding='binary', minv=10, maxv=20, length=5)

chromosome = Chromosome(name='chr1', genes=(gen1, gen2), mutation_prob=1)
chromosome_copy = copy.deepcopy(chromosome)
```
Procudes this error:
```
Traceback (most recent call last):
  File "D:/OneDrive/Desktop/GA Optimization/example_main.py", line 12, in <module>
    chromosome_copy = copy.deepcopy(chromosome)
  File "D:\OneDrive\Joaquin\Software\Anaconda3\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\OneDrive\Joaquin\Software\Anaconda3\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\OneDrive\Joaquin\Software\Anaconda3\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "D:\OneDrive\Joaquin\Software\Anaconda3\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\OneDrive\Joaquin\Software\Anaconda3\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: 'NoneType' object is not callable
```

**Comment by ramazanpolat** [comment]
Solved with latest release 0.8.4.

@JoaquinRives.

Use this to update: `$ pip install -U prodict`
